version: '3.6'

services:

  postgres:
    container_name: postgres
    image: postgres:15.1
    ports:
    - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh          
      - postgres:/var/lib/postgresql/data    
    environment:
      TZ: "America/Cuiaba"
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  dataimport-ui:
    container_name: dataimport-ui
    image: ibmoreno/dataimport-ui:latest
    build: ./dataimport-ui
    depends_on:
      - dataimport-api
    ports:
      - "80:80"
    environment:
      TZ: "America/Cuiaba"

  dataimport-api:
    container_name: dataimport-api
    image: ibmoreno/dataimport-api:latest
    build: ./dataimport-api
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      TZ: "America/Cuiaba"
      SERVER_PORT: 8080
      JDBC_POSTGRES_URL: ${JDBC_POSTGRES_URL}
      JDBC_POSTGRES_USER: ${JDBC_POSTGRES_USER}
      JDBC_POSTGRES_PASSWORD: ${JDBC_POSTGRES_PASSWORD}
      MULTIPART_LOCATION: ${MULTIPART_LOCATION}
      OAUTH2_ISSUER_URI: ${OAUTH2_ISSUER_URI}

  keycloak:
    container_name: keycloak
    image: keycloak
    build:
      context: ./keycloak
      args:
        KEYCLOAK_VERSION: 22.0.0
    command: ['start', '--optimized']
    depends_on:
      - "postgres"
    environment:
      JAVA_OPTS_APPEND: -Dkeycloak.profile.feature.upload_scripts=enabled
      KC_DB_URL: ${KC_DB_URL}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KC_DB_USERNAME: ${KC_DB_USERNAME}
      KC_HEALTH_ENABLED: 'true'
      KC_HTTP_ENABLED: 'true'
      KC_METRICS_ENABLED: 'true'
      KC_HOSTNAME_URL: ${KC_HOSTNAME_URL}
      KC_HOSTNAME_PORT: ${KC_HOSTNAME_PORT}
      KC_HOSTNAME_STRICT: 1
      KC_PROXY: reencrypt
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8180:8080"
      - "8787:8787" # debug port

volumes:
  postgres: 
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./database/postgres/data      