version: '3.6'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
    - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data
