server:
  port: ${SERVER_PORT:8080}

spring:
  servlet:
    multipart:
      enabled: true
      location: ${MULTIPART_LOCATION:/tmp}
      max-file-size: 20MB
      max-request-size: 20MB

  datasource:
    url: ${JDBC_POSTGRES_URL:jdbc:postgresql://localhost:5432/data_import}
    driver-class-name: org.postgresql.Driver
    username: ${JDBC_POSTGRES_USER:user_import}
    password: ${JDBC_POSTGRES_PASSWORD:user_import}

  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER_URI:http://kubernetes.docker.internal.org:8180/realms/dataimport}

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true

logging:
  level:
    root: info
    com.dataimport.api: info