server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:postgresql://localhost:5432/data_import
    driver-class-name: org.postgresql.Driver
    username: user_import
    password: user_import

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true