server:
  port: ${SERVER_PORT:8080}

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: ${JDBC_POSTGRES_URL:jdbc:postgresql://localhost:5432/data_import}
    driver-class-name: org.postgresql.Driver
    username: ${JDBC_POSTGRES_USER:user_import}
    password: ${JDBC_POSTGRES_PASSWORD:user_import}

  jpa:
    hibernate:
      ddl-auto: none

  flyway:
    enabled: true